FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++ git

COPY package*.json ./

RUN npm ci --legacy-peer-deps

COPY . .

COPY .env.development ./.env

EXPOSE 3000 8000

CMD ["npm", "run", "dev"]